/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import entity.Payment;
import ADT.ArrayList;
import ADT.ListInterface;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import java.util.Iterator;

/**
 *
 * @author User
 */
public class MakePaymentUI extends javax.swing.JPanel {

    private ListInterface<Payment> paymentList = new ArrayList<>();
    private int position = -1;
//    private int paymentID = 1000;
//    private ListInterface<Payment> paymentList = new ArrayList<>();

    /**
     * Creates new form MakePaymentUI
     */
    public MakePaymentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbTitle = new javax.swing.JLabel();
        jrbOnlineBanking = new javax.swing.JRadioButton();
        jrbTNG = new javax.swing.JRadioButton();
        jrbGrabPay = new javax.swing.JRadioButton();
        jtfName = new javax.swing.JTextField();
        jtfAppointment = new javax.swing.JTextField();
        jtfDate = new javax.swing.JTextField();
        jtfTime = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        jbtConfirm = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jbtDisplay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlbTitle1 = new javax.swing.JLabel();
        jlbMethod = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbAppointment = new javax.swing.JLabel();
        jlbDate = new javax.swing.JLabel();
        jlbTime = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        jtfEditUserName = new javax.swing.JTextField();
        jtfEditAppointment = new javax.swing.JTextField();
        jtfEditDate = new javax.swing.JTextField();
        jtfEditTime = new javax.swing.JTextField();
        jtfEditPrice = new javax.swing.JTextField();
        jtfEditPaymentMethod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaPayment = new javax.swing.JTextArea();
        jbtEdit = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jbtReset = new javax.swing.JButton();
        jlbName1 = new javax.swing.JLabel();
        jlbDate1 = new javax.swing.JLabel();
        jlbTime1 = new javax.swing.JLabel();
        jlbAppointment1 = new javax.swing.JLabel();
        jlbMethod1 = new javax.swing.JLabel();
        jlbPrice2 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlbTitle.setText("Your Appointment:");

        buttonGroup1.add(jrbOnlineBanking);
        jrbOnlineBanking.setText("FPX Online Banking");
        jrbOnlineBanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOnlineBankingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbTNG);
        jrbTNG.setText("TNG E-wallet");
        jrbTNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTNGActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbGrabPay);
        jrbGrabPay.setText("Grab pay");

        jtfName.setText("Tan Yee Yao");
        jtfName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jtfNameComponentShown(evt);
            }
        });
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });

        jtfAppointment.setText("Body check up");

        jtfDate.setText("8/9/2022");

        jtfTime.setText("8:00am");
        jtfTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTimeActionPerformed(evt);
            }
        });

        jtfPrice.setText("RM350");
        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });

        jbtConfirm.setText("Confirm");
        jbtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmActionPerformed(evt);
            }
        });

        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtDisplay.setText("Display");
        jbtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDisplayActionPerformed(evt);
            }
        });

        jlbTitle1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlbTitle1.setText("Manage Payment:");

        jlbMethod.setText("Payment Method:");

        jlbName.setText("User:");

        jlbAppointment.setText("Appointment:");

        jlbDate.setText("Date:");

        jlbTime.setText("Time:");

        jlbPrice.setText("Price:");

        jtfEditAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditAppointmentActionPerformed(evt);
            }
        });

        jtaPayment.setColumns(20);
        jtaPayment.setRows(5);
        jScrollPane1.setViewportView(jtaPayment);

        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });

        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });

        jbtReset.setText("Reset");
        jbtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbName)
                            .addComponent(jlbAppointment)
                            .addComponent(jlbDate)
                            .addComponent(jlbTime)
                            .addComponent(jlbPrice)
                            .addComponent(jlbMethod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEditAppointment)
                            .addComponent(jtfEditDate)
                            .addComponent(jtfEditTime)
                            .addComponent(jtfEditPrice)
                            .addComponent(jtfEditPaymentMethod)))
                    .addComponent(jlbTitle1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jbtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jbtReset))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitle1)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbName)
                            .addComponent(jtfEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbAppointment)
                            .addComponent(jtfEditAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDate)
                            .addComponent(jtfEditDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTime)
                            .addComponent(jtfEditTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPrice)
                            .addComponent(jtfEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMethod)
                    .addComponent(jtfEditPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtEdit)
                    .addComponent(jbtDelete)
                    .addComponent(jbtReset))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jlbName1.setText("User:");

        jlbDate1.setText("Date:");

        jlbTime1.setText("Time:");

        jlbAppointment1.setText("Appointment:");

        jlbMethod1.setText("Payment Method:");

        jlbPrice2.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbName1)
                                    .addComponent(jlbAppointment1)
                                    .addComponent(jlbDate1)
                                    .addComponent(jlbTime1)
                                    .addComponent(jlbMethod1)
                                    .addComponent(jlbPrice2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jrbOnlineBanking)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jrbTNG))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jbtConfirm)
                                                .addGap(4, 4, 4)
                                                .addComponent(jbtDisplay)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbtCancel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbGrabPay))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfDate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfAppointment, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAppointment1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTime1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOnlineBanking)
                    .addComponent(jrbTNG)
                    .addComponent(jrbGrabPay)
                    .addComponent(jlbMethod1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbOnlineBankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOnlineBankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbOnlineBankingActionPerformed

    private void jrbTNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTNGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTNGActionPerformed

    private void jbtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmActionPerformed
        // TODO add your handling code here:
        
        String userName = jtfName.getText();
        String appointment = jtfAppointment.getText();
        String date = jtfDate.getText();
        String time = jtfTime.getText();
        String price = jtfPrice.getText();
        jrbOnlineBanking.setActionCommand("FPX Online Banking");
        jrbTNG.setActionCommand("TNG E-wallet");
        jrbGrabPay.setActionCommand("Grab Pay");
        String paymentMethod = getSelectedButtonText(buttonGroup1);
//        int entry = paymentList.getNumberOfEntries();

        if (paymentMethod == null) {
            JOptionPane.showMessageDialog(this, "Please select payment method!");
        } else {
            JOptionPane.showMessageDialog(this, "Payment is made successfully");

            Payment payment = new Payment(userName, appointment, date, time, price, paymentMethod);
            paymentList.add(payment);

        }
    }//GEN-LAST:event_jbtConfirmActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void jtfTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTimeActionPerformed

    private void jtfNameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtfNameComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfNameComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jtfName.setEditable(false);
        jtfAppointment.setEditable(false);
        jtfDate.setEditable(false);
        jtfTime.setEditable(false);
        jtfPrice.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDisplayActionPerformed
        // TODO add your handling code here:

        jtaPayment.setText("");
        jtaPayment.append("Username\tAppointment\tDate\tTime\tPrice\tPaymentMethod  \n");
        Iterator<Payment> it = paymentList.getIterator();
        while (it.hasNext()) {
            Payment pay = it.next();
            jtaPayment.append(pay.getUserName() + "\t");
            jtaPayment.append(pay.getAppointment() + "\t");
            jtaPayment.append(pay.getDate() + "\t");
            jtaPayment.append(pay.getTime() + "\t");
            jtaPayment.append(pay.getPrice() + "\t");
            jtaPayment.append(pay.getPaymentMethod() + "\n");
        }
//        jtaPayment.append(paymentList.getEntry(1).toString());
    }//GEN-LAST:event_jbtDisplayActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        // TODO add your handling code here:
        String newuserName = jtfEditUserName.getText();
        String newappointment = jtfEditAppointment.getText();
        String newdate = jtfEditDate.getText();
        String newtime = jtfEditTime.getText();
        String newprice = jtfEditPrice.getText();
        String newpaymentMethod = jtfEditPaymentMethod.getText();
        
        Payment newPayment = new Payment(newuserName,newappointment,newdate,newtime,newprice,newpaymentMethod);
        paymentList.replace(1, newPayment);
        jtaPayment.setText("");

        
    }//GEN-LAST:event_jbtEditActionPerformed

    private void jtfEditAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEditAppointmentActionPerformed

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        
        
//        if(jtfEditUserName.getText().equals()){
        Payment results = paymentList.remove(1);
        System.out.println(results.getUserName());
        jtaPayment.setText("");
        
        jtaPayment.append("Number of entry:" + Integer.toString(paymentList.getNumberOfEntries())+"\n");
        jtaPayment.append("Username\tAppointment\tDate\tTime\tPrice\tPaymentMethod  \n");
        Iterator<Payment> it = paymentList.getIterator();
        while (it.hasNext()) {
            Payment pay = it.next();
            jtaPayment.append(pay.getUserName() + "\t");
            jtaPayment.append(pay.getAppointment() + "\t");
            jtaPayment.append(pay.getDate() + "\t");
            jtaPayment.append(pay.getTime() + "\t");
            jtaPayment.append(pay.getPrice() + "\t");
            jtaPayment.append(pay.getPaymentMethod() + "\n");
        }
//        }
//        else{
//            JOptionPane.showMessageDialog(this, "Username does not found");
//        }
    }//GEN-LAST:event_jbtDeleteActionPerformed

    private void jbtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetActionPerformed
        // TODO add your handling code here:
        jtfEditUserName.setText("");
        String newappointment = jtfEditAppointment.getText();
        String newdate = jtfEditDate.getText();
        String newtime = jtfEditTime.getText();
        String newprice = jtfEditPrice.getText();
        String newpaymentMethod = jtfEditPaymentMethod.getText();
        
    }//GEN-LAST:event_jbtResetActionPerformed
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakePaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakePaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakePaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakePaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakePaymentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtConfirm;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JButton jbtDisplay;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtReset;
    private javax.swing.JLabel jlbAppointment;
    private javax.swing.JLabel jlbAppointment1;
    private javax.swing.JLabel jlbDate;
    private javax.swing.JLabel jlbDate1;
    private javax.swing.JLabel jlbMethod;
    private javax.swing.JLabel jlbMethod1;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbName1;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JLabel jlbPrice2;
    private javax.swing.JLabel jlbTime;
    private javax.swing.JLabel jlbTime1;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbTitle1;
    private javax.swing.JRadioButton jrbGrabPay;
    private javax.swing.JRadioButton jrbOnlineBanking;
    private javax.swing.JRadioButton jrbTNG;
    private javax.swing.JTextArea jtaPayment;
    private javax.swing.JTextField jtfAppointment;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfEditAppointment;
    private javax.swing.JTextField jtfEditDate;
    private javax.swing.JTextField jtfEditPaymentMethod;
    private javax.swing.JTextField jtfEditPrice;
    private javax.swing.JTextField jtfEditTime;
    private javax.swing.JTextField jtfEditUserName;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfTime;
    // End of variables declaration//GEN-END:variables
}
