/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import ADT.LinkedList;
import ADT.ListInterfaces;
import entity.medicine;
import java.util.Iterator;
import javax.swing.*;

/**
 *
 * @author Tee Kai Nee
 */
public class MedicineStock extends javax.swing.JPanel {
    ListInterfaces<medicine> linkedList = new LinkedList<>();
    medicine mdc = new medicine();
    
    public MedicineStock() {
        initComponents();
        jlbYesNo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlbMedicine = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jbtUpdate = new javax.swing.JButton();
        jbtDisplay = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jlbCategory = new javax.swing.JLabel();
        jlbDescriptions = new javax.swing.JLabel();
        jbtInsert = new javax.swing.JButton();
        jtfName = new javax.swing.JTextField();
        jlbQuantity = new javax.swing.JLabel();
        jtfQuantity = new javax.swing.JTextField();
        jlbSearch = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaDescriptions = new javax.swing.JTextArea();
        jlbPrice = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jcbCategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaData = new javax.swing.JTextArea();
        jtfSearch = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jlbYesNo = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jlbMedicine.setBackground(new java.awt.Color(255, 255, 255));
        jlbMedicine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbMedicine.setText("Medicine Stock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jlbMedicine)
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMedicine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbName.setText("Medicine Name:");

        jbtUpdate.setBackground(new java.awt.Color(204, 255, 255));
        jbtUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        jbtDisplay.setBackground(new java.awt.Color(255, 255, 204));
        jbtDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtDisplay.setText("Display");
        jbtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDisplayActionPerformed(evt);
            }
        });

        jbtDelete.setBackground(new java.awt.Color(255, 102, 102));
        jbtDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });

        jlbCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbCategory.setText("Category:");

        jlbDescriptions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbDescriptions.setText("Descriptions:");

        jbtInsert.setBackground(new java.awt.Color(204, 255, 204));
        jbtInsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtInsert.setText("Insert");
        jbtInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInsertActionPerformed(evt);
            }
        });

        jlbQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbQuantity.setText("Quantity:");

        jlbSearch.setText("Search:");

        jtaDescriptions.setColumns(20);
        jtaDescriptions.setRows(5);
        jScrollPane3.setViewportView(jtaDescriptions);

        jlbPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbPrice.setText("Price:");

        jcbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Antianginals", "Cataract", "Diabetes", "Vertigo" }));

        jtaData.setColumns(20);
        jtaData.setRows(5);
        jScrollPane1.setViewportView(jtaData);

        jbtSearch.setText("Search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        jlbYesNo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbName)
                                    .addComponent(jlbDescriptions)
                                    .addComponent(jlbQuantity)
                                    .addComponent(jlbPrice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbYesNo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCategory)
                            .addComponent(jcbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDescriptions)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPrice)
                            .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbQuantity)
                            .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtInsert)
                            .addComponent(jbtDisplay)
                            .addComponent(jbtUpdate)
                            .addComponent(jbtDelete))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSearch)
                            .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtSearch)
                            .addComponent(jlbYesNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
         String name = jtfName.getText();
         String category = jcbCategory.getSelectedItem().toString();
         String descriptions = jtaDescriptions.getText();
         double price = Double.parseDouble(jtfPrice.getText());
         int quantity = Integer.parseInt(jtfQuantity.getText());
         
         mdc = new medicine(name, category,descriptions,price,quantity);
         linkedList.remove(1);
    }//GEN-LAST:event_jbtDeleteActionPerformed

    private void jbtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDisplayActionPerformed
            jtaData.append("Name\tCategory\tDescription\t\tPrice\tQuantity\n");
            Iterator<medicine> it = linkedList.getIterator();
            while(it.hasNext()){
                medicine item = it.next();
                jtaData.append(item.getName() + "\t" + item.getCategory() + "\t" + item.getDescriptions() + "\t\t" + "RM" + item.getPrice() + "\t" + item.getQuantity() + "\n\n");
            }
    }//GEN-LAST:event_jbtDisplayActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
         String name = jtfName.getText();
         String category = jcbCategory.getSelectedItem().toString();
         String descriptions = jtaDescriptions.getText();
         double price = Double.parseDouble(jtfPrice.getText());
         int quantity = Integer.parseInt(jtfQuantity.getText());
         
         mdc = new medicine(name, category,descriptions,price,quantity);
         linkedList.replace(1,mdc);
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jbtInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInsertActionPerformed
         String name = jtfName.getText();
         String category = jcbCategory.getSelectedItem().toString();
         String descriptions = jtaDescriptions.getText();
         double price = Double.parseDouble(jtfPrice.getText());
         int quantity = Integer.parseInt(jtfQuantity.getText());
       
         mdc = new medicine(name,category,descriptions,price,quantity);
         linkedList.add(1,mdc);
        
        JOptionPane.showConfirmDialog(null, "Inserted Successfully", "Information Message", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_jbtInsertActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        String search = jtfSearch.getText();
        
        boolean data = linkedList.contains(mdc);
        jlbYesNo.setVisible(true);
        if(data == true){
            jlbYesNo.setText("Exist");
        }else{
            jlbYesNo.setText("Not Exist");
        }
    }//GEN-LAST:event_jbtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JButton jbtDisplay;
    private javax.swing.JButton jbtInsert;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JLabel jlbCategory;
    private javax.swing.JLabel jlbDescriptions;
    private javax.swing.JLabel jlbMedicine;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JLabel jlbQuantity;
    private javax.swing.JLabel jlbSearch;
    private javax.swing.JLabel jlbYesNo;
    private javax.swing.JTextArea jtaData;
    private javax.swing.JTextArea jtaDescriptions;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfQuantity;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
